export const DEFAULT_PRODUCT_FORM = {
  sku: "",
  barcode: "",
  name: "",
  description: "",
  categoryId: "",
  brand: "",
  manufacturer: "",
  weight: "",
  dimensions: "",
  tags: "",
  isFeatured: false,
  basePrice: 0,
  costPrice: 0,
  discountPrice: 0,
  stockUnits: 0,
  lowStockAlert: 10,
  metaTitle: "",
  metaDescription: "",
};
